name: Docker Image CI

on:
  pull_request:
    paths:
    - 'python/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./python
        echo "${{ secrets.DOCKERPW }}" | docker login -u "arjunadilan" --password-stdin
        docker image build -t arjunadilan/gitops:hellov1.2.3 .
        docker push arjunadilan/gitops:hellov1.2.3
