name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "!$Perfume90210" | docker login -u "arjunadilan" --password-stdin
        docker image build -t arjunadilan/gitops:hellov1.0 .
        docker push arjunadilan/gitops:hellov1.0
