apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lasample
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    labels:
      app: hello
    spec:
      containers:
        - name: hello
          image: arjunadilan/gitops:hellov1.2.3